CREATE DATABASE finalproject;

CREATE TABLE employee(
	age INT,
    attrition VARCHAR(50), 
    businesstravel VARCHAR(50),
    dailyrate BIGINT,
    department VARCHAR(50),
    distancefromhome INT,
    education INT,
    educationfield VARCHAR(50),
    employeecount INT,
    employeenumber INT,
    environmentsatisfaction INT, 
    gender VARCHAR(50),
    hourlyrate BIGINT,
    jobinvolvement INT,
    joblevel INT, 
    jobrole INT, 
    jobsatisfaction INT, 
    maritalstatus VARCHAR(50),
    monthlyincome BIGINT, 
    monthlyrate BIGINT,
    numcompaniesworked INT,
    over18 VARCHAR(50),
    overtime VARCHAR(50),
    percentsalaryhike INT,
    performancerating INT,
    relationshipsatisfaction INT,
    standardhours INT,
    stockoptionlevel INT,
    totalworkingyears INT,
    trainingtimeslastyear INT,
    worklifebalance INT,
    yearsatcompany INT,
    yearsincurrentrole INT,
    yearssincelastpromotion INT,
    yearswithcurrmanager INT);